spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 기획서 상의 MySQL 거래·사용자 DB 지정 및 stock_db 방 연동
    url: jdbc:mysql://localhost:3306/stock_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root
    password: kidsuk789@

  jpa:
    hibernate:
      # 서버가 켜질 때 엔티티(테이블) 구조를 분석해서 자동으로 MySQL에 테이블을 생성/업데이트해 주는 옵션
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # 기획서 4.3 성능 최적화: N+1 문제 방지를 위한 배치 페치 사이즈 설정
        default_batch_fetch_size: 100

  # 기획서 2.2 기술 스택: 실시간 시세 캐시 및 동시성 제어용 Redis 설정
  data:
    redis:
      host: localhost
      port: 6379

  # 기획서 2.2 기술 스택: 스프링 시큐리티 가림막 임시 우회 설정
  security:
    user:
      name: admin
      password: admin

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

